export const TYPES = {
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    RESET_CART: 'RESET_CART'
}

