import Head from 'next/head'
import { HeaderSection } from '../components/01-sections/HeaderSection'
import { CartSection } from '../components/01-sections/CartSection'
import { NomeProvider } from '../context/store'
import '../styles/styles.scss'

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Nomennescio - Store</title>
				<meta name="Nomennescio | Store" content="Generated by Ricardo Oliva Alonso" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>

			<NomeProvider>
				<div className='app'>
					<HeaderSection />
					<Component {...pageProps} />
					<CartSection />
				</div>
			</NomeProvider>
		</>
	)
}


export default MyApp
